### ISSUE TITLE
Not working for SCSS files

### ISSUE THREAD

**Issue by drawcard** [guiguan/file-header#1]
Hi,

When I run "File Header" > "Add Header" no comment blocks are added to the file.

Using Atom 1.4.3 on Mac OSX El Capitan

**Comment by guiguan** [comment]
I could add header for SCSS files without problem. Could you try the following steps:

1. Restart your Atom. 
2. Open your Developer Tools (<kbd>alt-cmd-i</kbd>) and see if there is any error

**Comment by drawcard** [comment]
Just tried it again - nothing seems to be inserted :cry: 

Here's the output:

![image](https://cloud.githubusercontent.com/assets/1435638/12839239/5f738b12-cc27-11e5-996c-ef9cc3a7117d.png)

**Comment by guiguan** [comment]
Hmm, indeed very strange. Are you able to access the settings of File Header package?

**Comment by guiguan** [comment]
@drawcard It seemed that this problem only happened to you. I guess it might be something related to your Atom configuration. I will close for now. Let me know if you need my further investigation.
