### ISSUE TITLE
Atom 1.7.2 with file-header

### ISSUE THREAD

**Issue by drxos** [guiguan/file-header#17]
Hey.

I installed file-header. Unfortunetly, it just works with cson files. How can you help ?

**Comment by guiguan** [comment]
I am using 1.7.2 too. It works fine. Can you explain your problem in details?

**Comment by drxos** [comment]
I need to complete my python files generate using django. But when cmd+shift+H, I did not see any change. I have the same issue with others files. It works only for .cson files.

**Comment by drxos** [comment]
## my config.cson

```
"*":
  "auto-copyright": {}
  core:
    disabledPackages: [
      "vim-mode"
    ]
    themes: [
      "atom-material-ui"
      "atom-material-syntax-dark"
    ]
  "file-header":
    autoAddingHeaderEnabled: true
    email: "sounton@gmail.com"
    realname: "Hodonou SOUNTON"
    username: "iker"
  welcome:
    showOnStartup: false
".source.python":
  "file-header":
    autoAddingHeaderEnabled: false
".gfm.source":
  "file-header":
    autoAddingHeaderEnabled: false
    username: "drxos"
".plain.text":
  "file-header":
    autoAddingHeaderEnabled: true


```

**Comment by drxos** [comment]
I am waiting for your response please. @guiguan

**Comment by guiguan** [comment]
If you restart your Atom, will it work?

**Comment by drxos** [comment]
No.

**Comment by guiguan** [comment]
@drxos Normally, you can configure file-header from its settings (<kbd>cmd+,</kbd> > Packages > file-header). Can you open a Python file in Atom and press <kbd>cmd+alt+i</kbd> to open an inspector? When you try to add header, is there any error in the inspector's console?

**Comment by drxos** [comment]
Thank you for your back, @guiguan. In fact, I'm using Atom under Archlinux not Mac. So I don't have <kbd>cmd</kbd> touch. Consequence : I can not open an inspector. I check it also in the menu in vain. I saw file-header by pressing <kbd>ctrl</kbd><kbd>,</kbd>. 
Regards.

**Comment by guiguan** [comment]
@drxos Don't worry. I will install a copy of Arch Linux and test it out myself. I am a fan of Arch Linux too :D

**Comment by drxos** [comment]
Ok. Great, @guiguan. I' still waiting fofr you. Have a nice day.

**Comment by drxos** [comment]
I fixed the issue and I request a pull.

Keep in touch

**Comment by guiguan** [comment]
Nice to hear :)
