### ISSUE TITLE
Auto header on saving new files

### ISSUE THREAD

**Issue by MiMaMuh** [guiguan/file-header#2]
Hi, it would be great if the header is automatically created when I save a new file for the first time.

**Comment by guiguan** [comment]
@MiMaMuh I added this feature in v1.2.0. Please upgrade :)

**Comment by MiMaMuh** [comment]
Thanks. Currently it doesn't work for me when I create a new js file. don't know why. I'm using 1.4.1.

Does it work for you? 
By the way: could you add source.js.jsx to the list too? It would be great!

**Comment by guiguan** [comment]
Thanks for your pull request. It seems that "source.js.rails source.js.jquery" as a whole is a scope name. I guess this is because the js.rails and js.jquery share a similar syntax. So after I moved "source.js.jsx" to a separate mapping. It works. Check out v1.5.0.
