### ISSUE TITLE
Won't recognise custom templates

### ISSUE THREAD

**Issue by liamegan** [guiguan/file-header#22]
I have custom templates set up under _~/.atom/file-header/_ lang-mapping as follows:
`{
  "source.js": "JS.tmpl",
  "source.scss": "SCSS.tmpl"
}
`
And a folder under there called templates that contains both JS.tmpl and SCSS.tmpl. I receive the following error when saving js files:

> Uncaught Error: ENOENT: no such file or directory, open '/Users/user/.atom/packages/file-header/lib/templates/JS.tmpl'

And saving a scss file reverts to the old header (presumably saved in the package directory).

**Comment by guiguan** [comment]
Can you make sure that `/Users/user/.atom/packages/file-header/lib/templates/JS.tmpl` actually exists?
