### ISSUE TITLE
Ability to specify project name on a per project basis

### ISSUE THREAD

**Issue by gilesbutler** [guiguan/file-header#26]
It would be great to have the ability to specify the project name for each project rather than globally in the settings.

Not sure the best place to set it, maybe it could work with https://atom.io/packages/project-manager

**Comment by guiguan** [comment]
@gilesbutler Yep, you can use `project-manager` to do that. In your `projects.cson`, you can put things like:

```cson
[
  {
    title: "Demo Project"
    paths: [
      "/Users/guiguan/Documents/Projects/demo-project"
    ]
    settings:
      'file-header.projectName': 'Your Project Name'
  }
]
```

**Comment by gilesbutler** [comment]
Thanks @guiguan :)
