### ISSUE TITLE
Ctr + Z revert the last modified date 

### ISSUE THREAD

**Issue by hyyan** [guiguan/file-header#33]
Thanks for the amazing work , 

How to prevent the Ctr + Z from reverting the modified date

**Comment by guiguan** [comment]
You can save it again to give it a new timestamp. Every change to the text buffer is recorded. I doubt there is a way to prevent the reversion.

**Comment by hyyan** [comment]
` Every change to the text buffer is recorded.` , I think the job done by this extension must not be recorded to the buffer , at lease there must a way around it .

What do you think ?

**Comment by guiguan** [comment]
@hyyan Oh, I see your point. So you want <kbd>cmd+z</kbd> to directly revert last change of your code instead of a timestamp?

**Comment by hyyan** [comment]
@guiguan  correct

**Comment by hyyan** [comment]
@guiguan  Any hope with that ?

**Comment by guiguan** [comment]
yes. I ll push a update later

**Comment by hyyan** [comment]
@guiguan Amazing , thanks , Keep it up 👍

**Comment by guiguan** [comment]
@hyyan Fixed in b246ab8

**Comment by hyyan** [comment]
@guiguan Awesome , works perfectly , great support 👍
