### ISSUE TITLE
file-header is not working?

### ISSUE THREAD

**Issue by useralive003** [guiguan/file-header#35]
i have installed file-header in atom but its not working can you please help me out

**Comment by guiguan** [comment]
@useralive003 can you post the error msg you hv got from dev console?

**Comment by jcrsilva** [comment]
Yep, ain't working for me too.

Doesn't work from the packages menu or from the shortcut.

I get nothing in the dev console.

Is there anything else I can do to try and debug this?

**Comment by guiguan** [comment]
What file types are you trying to add headers to?

**Comment by bdmorin** [comment]
I just tried this for the first time today, and it won't add the file header for me. I have no errors displayed.

**Comment by guiguan** [comment]
Guys, I deliberately removed `text.plain.null-grammar` lang, which is the default grammar for new files (<kbd>cmd+n</kbd>), from supported lang list. If you change your lang to something else, for example, Javascript, it should work. Now, I am adding back the `text.plain.null-grammar` but keeping it in ignored list. This should be less confusing.

**Comment by guiguan** [comment]
Please upgrade to [v1.13.4](https://github.com/guiguan/file-header/releases/tag/v1.13.4). I will close the issue for now. Let me know how it goes
