### ISSUE TITLE
Not working in .vue file

### ISSUE THREAD

**Issue by focus7eleven** [guiguan/file-header#39]
It seems that file-header is not working in .vue file.
Is is possible to support .vue file in the coming future?

**Comment by hgt803** [comment]
can not work in vue

**Comment by hgt803** [comment]
just do it
in /Users/userName/.atom/packages/file-header/lib/lang-mapping.json 
add   "text.html.vue": "HTML.tmpl",

**Comment by guiguan** [comment]
@hgt803 do you want to make a pull request so I can merge? :P
