### ISSUE TITLE
Compatibility Issue with the Sublime FileHeader Package

### ISSUE THREAD

**Issue by plzh** [guiguan/file-header#4]
Hi, I really appreciate your effort to make this great package. I just found an issue that this plugin cannot update file headers generated with the Sublime FileHeader plugin. 

This plugin recognizes (case sensitive): 
```
% @Last modified by:  
% @Last modified time: 
```
However, the Sublime FileHeader plugin generates:
```
% @Last Modified by:  
% @Last Modified time:
```
This can be fixed by ignoring the case while parsing the fields. I think the fix will be very helpful for people switching from Sublime to atom while having to worked with existing code.

**Comment by guiguan** [comment]
Thanks for your suggestion. I have added an option to ignore cases in template fields in v1.3.1. Check it out!
