### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by F4OST** [guiguan/file-header#46]
Since the last update I can't savemy file anymore and my sure its caused by file-header, when I disable it I can save my file.

**Comment by guiguan** [comment]
What version of `Atom` are you using?

**Comment by F4OST** [comment]
I'm using `Atome 1.20.1`

**Comment by guiguan** [comment]
Can you try `Atom 1.21.0`?

**Comment by F4OST** [comment]
The package work on `Atom 1.21.0` but not on `Atome 1.20.1`

**Comment by guiguan** [comment]
Yes, `Atom`'s API has been changed since `1.21.0`, so you have to use new versions in order to use this package
