### ISSUE TITLE
Cannot update header without '@'

### ISSUE THREAD

**Issue by mjmaix** [guiguan/file-header#52]
Hi, 

My new team uses this template on Sublime's https://github.com/shiyanhui/FileHeader I want to continue working on Atom

this does not work
```
/* # ---------------------------------------------
# ---------------------------------------------
# Author: {{author}}
# Date:   {{create_time}}
# Last Modified by: {{last_modified_by}}
# Last Modified time: {{last_modified_time}}
# ---------------------------------------------
# --------------------------------------------- */
```

but this works

```
/* # ---------------------------------------------
# ---------------------------------------------
# @Author: {{author}}
# @Date:   {{create_time}}
# @Last Modified by: {{last_modified_by}}
# @Last Modified time: {{last_modified_time}}
# ---------------------------------------------
# --------------------------------------------- */

```

This doesn't work on this plugin and it justs add a new header to the update. I noticed that adding '@' before the fields works but my team doesn't want to modify their existing template since it is already working fine on sublime and doesn't want to trigger changes.

Is there a way to for the fields to updated properly without '@'? I've already read the code . and try to hack a little by removing the '@' but failed.

**Comment by mjmaix** [comment]
I've posted a bounty on this issue -> https://www.bountysource.com/issues/55359650-cannot-update-header-without @guiguan can you check?

**Comment by AntoineGagnon** [comment]
Changed the way the templates look and how the regex check is done. I assumed you will always have **# Text** for you keywords. You can see my fork [here](https://github.com/AntoineGagnon/file-header). 
To test it you can clone my repo and use
```
apm link --dev
atom --dev
```
This way you can test it in a dev environment. If you want to keep the changes in your standard version of atom, you can just remove the **--dev** flags

**Comment by guiguan** [comment]
@mjmaix no bounty is needed :) I will look into this as well as some minor bugs that I have already fixed.

In the meantime, you can probably use @AntoineGagnon’s workaround

**Comment by mjmaix** [comment]
Hi @AntoineGagnon,
Working :) very much appreciated. You can claim the bounty

@guiguan,

Will do. Just want to extend my thanks for this repo as well 👍

**Comment by AntoineGagnon** [comment]
No problem @mjmaix ! You still need to close the issue for me to claim it :+1:
