### ISSUE TITLE
Won't update header

### ISSUE THREAD

**Issue by Asbra** [guiguan/file-header#9]
Hi. I have a header already in my projects (been using FileHeader for ST3)

Here's an example:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @author      Johan/Asbra.net
# @date        2016-01-12 11:20:26
# @modified_by Johan/Asbra.net
# @modified_at 2016-02-21 20:15:13
```

So I set up Python.tmpl:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @author      {{author}}
# @date        {{create_time}}
# @modified_by {{author}}
# @modified_at {{last_modified_time}}
```

and mapped `"source.python": "Python.tmpl",`

However it does not update it

**Comment by guiguan** [comment]
I think you have to add a colon after each field name, for example: `@modified_by: {{author}}`.
